
# not tested,network configuration file should be modified both controller and compute nodes
# 
---
- hosts: controller 
  user: heat-admin 
  sudo: yes       
  sudo_user: root  
  tasks:
  - name: edit network configuration file
    commands: "{{item}}"
    with_items:
     -  sed -e '10cNETMASK=255.255.255.0' /etc/sysconfig/network-scripts/ifcfg-br-ex
     -  sed -e '1cdefault via 192.168.32.1 dev br-ex' /etc/sysconfig/network-scripts/route-br-ex
    notify:
    - restart network 
  handlers:
    - name: restart network 
      service: name=network state=restarted