---
- hosts: compute 
  sudo: yes       
  tasks:
  - name: edit compute network configuration file
    shell: sed -i '9cNETMASK=255.255.255.0' /etc/sysconfig/network-scripts/ifcfg-eth2 && sed -i '1c0.0.0.0/0 via 192.168.32.1 dev eth2' /etc/sysconfig/network-scripts/route-eth2
    notify:
    - restart network 
  handlers:
    - name: restart network 
      service: name=network state=restarted